### ISSUE TITLE
Support for binary number format

### ISSUE THREAD

**Issue by p4l1ly** [chyh1990/yaml-rust#113]
By this specification, there are more number formats than just decimal, binary and octal. Particularly the binary format is quite useful.

**Comment by pickfire** [comment]
@p4l1ly What should we do with this? Is this somewhat related to https://github.com/dtolnay/serde-yaml/issues/91?

**Comment by p4l1ly** [comment]
the related PR has been closed, so I think the issue can be also closed

**Comment by p4l1ly** [comment]
and yes, it is related to the dtolnay/serde-yaml#91 where my pull request has been paradoxically merged.

**Comment by stappersg** [comment]
@p4l1ly 

> so I think the issue can be also closed


Please do
