### ISSUE TITLE
Error on comment mark (`#`)

### ISSUE THREAD

**Issue by sekineh** [chyh1990/yaml-rust#121]
https://github.com/jgarber/redcloth/blob/RELEASE_3_0_4/tests/lists.yml#L1
produces error:
```
error: expected `[`, found `Bret`
 --> src\../test/fixture/redcloth3/lists.yml:1:7
  |
1 | --- # Bret Pettichord, Thanks.
  |       ^^^^ expected `[`
```

https://yaml.org/spec/1.2/spec.html#comment//

> 6.6. Comments
> An explicit comment is marked by a “#” indicator. Comments are a presentation detail and must not be used to convey content information.

**Comment by dtolnay** [comment]
I can't tell what you are doing, but none of the issues you opened are coming from yaml-rust. I am going to close this along with #119 and #120.

**Comment by sekineh** [comment]
You are totally right, I was wrong and so sorry.

For record, I improperly used `include!` macro instead of `include_str!`.  
This is the cause of the problem I reported.
