### ISSUE TITLE
Appveyor CI is failing

### ISSUE THREAD

**Issue by mathstuf** [chyh1990/yaml-rust#139]
The `cfg-if` crate no longer supports 1.28.0, so it's failing on the build there. What's the preferred process? Bumping the test versions?

**Comment by palfrey** [comment]
This also currently breaks the Travis builds, but #145 fixes both

**Comment by XVilka** [comment]
This could be closed because it's green now: https://ci.appveyor.com/project/chyh1990/yaml-rust/builds/34017061
