### ISSUE TITLE
mapping key uniquness

### ISSUE THREAD

**Issue by thiolliere** [chyh1990/yaml-rust#19]
it seems to me that [YAML mappings require key uniqueness](http://www.yaml.org/spec/1.2/spec.html#id2764652) but yaml-rust doesn't complain while parsing a map with two same key.

**Comment by chyh1990** [comment]
I think most implementations (e.g. `libyaml`) do NOT warn about this problem. They just let the latter one wins. So we follow this convention to avoid compatibility issues.

**Comment by C4K3** [comment]
Would you accept a patch implementing any of the following ideas?

1. Add a feature flag that when enabled makes duplicate map entries an error
2. Add parallel strict functions, e.g. `load_from_str_strict`, possibly gated behind feature flag
3. Allow passing in an options struct such that one can dynamically choose between strict/not.
4. Allowing configurability by generic types, e.g. `load::<Lenient>` and `load::<Strict>` (for backwards compatibility the functions should probably be named something else.) This would in practice be similar to option 2 but would allow adding multiple options later without blowing up the number of functions.
