### ISSUE TITLE
the trait bound `std::io::Error: std::convert::From<yaml_rust::ScanError>` is not satisfied

### ISSUE THREAD

**Issue by ChrisMacNaughton** [chyh1990/yaml-rust#31]
If this trait were implemented, it would be possible to do:

``` rust
let docs = try!(YamlLoader::load_from_str(&s[..]));
```

rather than having to `unwrap()` or match As it stands, I have to match, and the convert the error myself instead of just being able to use try!().

**Comment by chyh1990** [comment]
Can you give me a concrete example for your use case? It seems that you want to convert ScanError to your own error type? ScanError is not an IO error anyway.
