### ISSUE TITLE
impl Error for ScanError

### ISSUE THREAD

**Issue by blaenk** [chyh1990/yaml-rust#4]
Would be nice if we could get an `Error` impl for `ScanError`, so we could easily use `try!` with `Yaml::load_from_str`.

**Comment by chyh1990** [comment]
`Error` trait has been implemented in https://github.com/chyh1990/yaml-rust/blob/master/src/scanner.rs#L53

Using `try!` is possible, can you show me your code?

**Comment by blaenk** [comment]
Thanks it works now with the new version.
