### ISSUE TITLE
Empty string should be quote

### ISSUE THREAD

**Issue by antoyo** [chyh1990/yaml-rust#41]
Hello.
I think I found an issue with my pull request #39:
I think that the empty string should be quoted, because otherwise, it will be parsed as a Unit.
Thanks.

**Comment by chyh1990** [comment]
Will 2d6a83d be enough?

**Comment by antoyo** [comment]
I'll make some tests to check if `trim()` is needed.
Thanks.

**Comment by antoyo** [comment]
I made some tests and quotes are also needed for a string with only spaces.
So I don't know exactly how it is parsed, but perhaps quotes are also needed when there are spaces at the start/end of a string.
In any case, your commit is not sufficient:
the case of a string like `"    "` will be emitted without quotes and the parser will try to parse it as a `Unit`.

**Comment by chyh1990** [comment]
I found a reference implementation here: https://github.com/adamkiss/LibYAML/blob/master/yaml/Escaper.php

We are also missing the single quoted part.

I think adding <TAB> and <SPACE> to the require quoted character is OK.

**Comment by antoyo** [comment]
I don't think adding SPACE to the required character is what we want.
For instance, if we have the string "my string", it can be emitted without quotes in YAML.
I don't know the precise rules about the spaces however. Do we need quotes when the string starts/ends with space?

**Comment by chyh1990** [comment]
Yeah, I get your point. But I think quoting something like "my string" is not a bad idea (the php version do this) and more robust. I'm not sure whether just quoting string starts/ends with space will introduce some corner cases?

**Comment by dtolnay** [comment]
I would strongly prefer not to quote strings unless necessary, even if it means we need to iterate on the heuristic a few times to get it right. Quoting for leading/trailing whitespace seems like a good start.

**Comment by chyh1990** [comment]
It looks good e52b058ae2fdfd341768aec0691e4ec9f3e6403a ?

**Comment by dtolnay** [comment]
e52b058ae2fdfd341768aec0691e4ec9f3e6403a: No need to check for starts_with or ends_with `'\t'` because any string containing `'\t'` anywhere will be quoted. Just check for `' '`.

**Comment by antoyo** [comment]
A style comment:
no need to use `return` in the last statement: just omit the semi-colon.

**Comment by chyh1990** [comment]
Closed by #46
