### ISSUE TITLE
integer values lose information

### ISSUE THREAD

**Issue by fabianschuiki** [chyh1990/yaml-rust#56]
`Yaml::Integer` does not allow for the verbatim value in the YAML file to be reconstructed. For example, `07054` and `7054` in the input file both map to `Yaml::Integer(7054)`. This is problematic, because the `07054` might have been intended to be a string, but was mistaken for an integer. By contrast, `Yaml::Real` does not have this issue, as it keeps the original string around: `07.054` and `7.054` map to `Yaml::Real("07.054")` and `Yaml::Real("7.054")` accordingly.

The same also holds for `Yaml::Null`, which is ambiguous in the sense that it could have been `~` or `null` in the input file. If the fields was intended to be interpreted as a string, the user of the library should be able to override the interpretation as `Yaml::Null` and access the original text.

Could we add a function to `Yaml` that returns the original verbatim string value given in the source file? This would imply changing `Yaml::Integer` to behave more like `Yaml::Real`, and adding a field to `Yaml::Null` that tracks which form of null was used. How about `pub fn as_raw_str(&self) -> &str` and `pub fn into_raw_string(&self) -> String`?

*Motivation:* I stumbled across this when trying to read a git commit from an input file which consists of only digits and has a leading 0.

**Comment by dtolnay** [comment]
Depending on your use case, if you are ascribing types to parts of your YAML input then you will likely be better off using serde_yaml. Even though it uses yaml-rust internally it does not have the problems you described. The yaml_rust::Yaml type is not designed for this use case.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde_yaml;

#[derive(Deserialize, Debug)]
struct S {
    looks_like_number: String,
    looks_like_null: String,
}

fn main() {
    let y = "looks_like_number: 07054\nlooks_like_null: ~";

    println!("{:?}", serde_yaml::from_str::<S>(y).unwrap());
}
```

**Comment by fabianschuiki** [comment]
@dtolnay: You make a good point. I will give serde_yaml a try to see if it covers my use case entirely. I fear that the YAML schema I'm trying to parse might be too relaxed, allowing strings as a short-hand for arrays in some places.

**Comment by dtolnay** [comment]
Check out this example in the docs of how to handle something like that. https://serde.rs/string-or-struct.html
