### ISSUE TITLE
Version 0.3.5 is on crates.io but not here

### ISSUE THREAD

**Issue by palfrey** [chyh1990/yaml-rust#59]
The Cargo.toml here specifies version 0.3.4, but https://crates.io/crates/yaml-rust/ has 0.3.5. I presume we're missing at least a commit that changes the version number, but possibly others?

**Comment by nox** [comment]
Could we get a reply on this please, @chyh1990?

**Comment by dtolnay** [comment]
I confirmed that no other commits are missing compared to the 0.3.5 on crates.io. I pushed acbdc9e7e420ebc0a82ceff1ecd9ffc8cc2b45fd which is identical to the code that was published as 0.3.5. I also pushed [tags](https://github.com/chyh1990/yaml-rust/releases) corresponding to all of the existing releases on crates.io.
