### ISSUE TITLE
Emitter tests have errors

### ISSUE THREAD

**Issue by bomgar** [chyh1990/yaml-rust#70]
I open a pull request to show what I mean

**Comment by alekratz** [comment]
For some reason, maps with array keys [emit with a `+ ` before them](https://github.com/chyh1990/yaml-rust/blob/24d1b0b0f822c38241c2761304ae5ee4f849bf8d/src/emitter.rs#L140), which causes the first item of the array to be interpreted as a string starting with `+ `.

**Comment by hoodie** [comment]
@alekratz I fixed that in #72

**Comment by alekratz** [comment]
Ah, thanks!

**Comment by hoodie** [comment]
@bomgar nice catch thank you very much 👍
I added the fixes to these bugs to #72 as well
