### ISSUE TITLE
Deserializer: Give client ownership of events

### ISSUE THREAD

**Issue by chris-m-h** [chyh1990/yaml-rust#74]
Disclaimer: I am new to Rust and maybe I misunderstand something.

Looking at the client libraries (yaml.rs in this project itself, de::Loader in serde-yaml), I realized that strings need to be cloned unnecessarily, as the EventReceiver interface does not pass ownership of the event.

Having implemented a small test client of serde-yaml myself, I realized that each string scalar was created three times on the heap: Once in yaml-rust, once in serde-yaml, and once in my client. If the EventReceiver passed ownership of the Event, one such allocation could be avoided.

I prepared an implementation myself to see if it works. If you want, I can prepare a pull request. But I would like to have your opinion on that before...

**Comment by dtolnay** [comment]
I agree, it should hand over the event by value. We would welcome a PR!

**Comment by chris-m-h** [comment]
When opening this issue I assumed that this project was a push parser.

However, after separating parser and event emitter while implementing PR #75, I realized that it is in reality a pull parser that is encapsulated in a push parser. The latter only validates the state machine model of the former.

Now I am not sure about the underlying reasons, but in my understanding, pull parsers are much more client friendly. I think it would be easy to change the parser to a pull parser.  If there is some interest in that I could propose a pull request once I have a bit of time.
