### ISSUE TITLE
alias support

### ISSUE THREAD

**Issue by hoodie** [chyh1990/yaml-rust#8]
Hey, I just noticed that alias were intended but are not fully implemented.
I could use this feature.
Could you finish it or perhaps give me some hints so I can do it?
Thank you.

**Comment by chyh1990** [comment]
Alias is on the TODO list. The scanner & parser do support alias, but the top level YamlLoader leaves it unimplemented. 

See https://github.com/chyh1990/yaml-rust/blob/master/src/yaml.rs#L140

I'll implement it next week if I have time :-)

**Comment by hoodie** [comment]
Hey, thanks. I'd already found that line, and started thinking about just sending you a PR, but I found it a bit too complicated for a quick contribution.

**Comment by hoodie** [comment]
Hey there :D

**Comment by chyh1990** [comment]
here's my implementation, not tested much

https://github.com/chyh1990/yaml-rust/tree/alias

**Comment by hoodie** [comment]
Thanks, I'll put it to the test?
