### ISSUE TITLE
Crates.io release is old

### ISSUE THREAD

**Issue by bomgar** [chyh1990/yaml-rust#81]
Hi,

the latest crates.io release is 8 months old. There're bugfixes (especially in the emitter) that are awesome. It would be great to have a new release with those fixes.

Thanks

**Comment by hoodie** [comment]
Release please 🤗

**Comment by hoodie** [comment]
Friendly reminder, that verson `0.3.5` on [crates.io](https://crates.io/crates/yaml-rust) is from Nov 25th, 2016. Especially the improvements in the `Emitter` are important to other crates like serde-yaml.

Release please 🤗

**Comment by hoodie** [comment]
Hi there, would you be so kind and release a new version of this crate?
Thank you

**Comment by hoodie** [comment]
Hey, the last release on crates.io is almost a year old. There are some critical fixes on master, and have been there for while now. Please make a release!

**Comment by jimmycuadra** [comment]
Maybe try emailing the maintainer directly to get their attention. It's possible they don't notice GitHub notifications.

**Comment by vroland** [comment]
As 0.4.0 is now on crates.io I think this one can be closed. Tanks a lot!

**Comment by hoodie** [comment]
@bomgar close plz 😊
