### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by matthiasbeyer** [chyh1990/yaml-rust#9]
Hi,

would love to get a release of this crate anytime soon, so I can pin my Cargo.toml to the release!

Please continue on this project, I find it useful!

**Comment by messense** [comment]
There is a release on crates.io:

https://crates.io/crates/yaml-rust/

FYI.

**Comment by chyh1990** [comment]
Yes, this crate is also hosted on crates.io. Maybe it is time to release 1.0?

**Comment by matthiasbeyer** [comment]
Whoops. Okay. Sorry for bothering you!

Anyways:

> Please continue on this project, I find it useful!

**Comment by hoodie** [comment]
As to releasing a 1.0, I wouldn't go there yet.
