### ISSUE TITLE
booleans quoted even when they are keys

### ISSUE THREAD

**Issue by ignatenkobrain** [chyh1990/yaml-rust#92]
```
"y": 2
```

I think this is wrong thing to do with **keys**. https://github.com/dtolnay/serde-yaml/pull/83#discussion_r152628088

**Comment by chyh1990** [comment]
@hoodie should it be treated differently when keywords are keys according to yaml spec?

**Comment by hoodie** [comment]
if it's the different treatment of say "y": ... and x: ..., why don't we just quote all keys in the export format? it's still valid yaml
