### ISSUE TITLE
Question: YamlLoader::load_from_str() vs. Yaml::load()

### ISSUE THREAD

**Issue by nguyendv** [chyh1990/yaml-rust#97]
As I understand, `Yaml::load()` loads a string to a Yaml object, while `YamlLoader::load_from_str()` loads a string to a vector of Yaml objects. In my use case, the vector's length is always 1.

1. In what cases `YamlLoader::load_from_str()` returns a vector with length > 1?
2. Which is recommended: `YamlLoader::load_from_str()` or `Yaml::load()`?

**Comment by nguyendv** [comment]
Answer for 1: a yaml file can contain multiple documents:
```
---
foo: bar
---
hue: hue
```

**Comment by chyh1990** [comment]
Ans 1: you're right, yaml supports multi-document file.

Ans 2: `YamlLoader::load_from_str()` provides the high level API, it returns `Yaml` object, which can be access like a hashmap. `Yaml:load()` provides the low level, event-based API, and you have to build the document tree on your own. For most users, `YamlLoader::load_from_str()` is enough.
